services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_ampl
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_ampl
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:8.2-apache
    container_name: php
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

volumes:
  db_data:
